name: react test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          docker
      - run: docker build -t testImage -f Dockerfile.dev .
      - run: docker run test npm run test -- --coverage