name: react test
on: [push]
jobs:
  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t testimage -f Dockerfile.dev .
      - run: docker run testimage npm run test -- --coverage